# Actuator health check config
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=healthcheck
management.endpoint.health.show-details=never
management.endpoint.health.enabled=true

# Default application root path
server.servlet.context-path=/alphabetical-company-search-consumer

server.port=${SERVER_PORT}
spring.kafka.bootstrap-servers=${BOOTSTRAP_SERVER_URL}

consumer.topic=${TOPIC}
consumer.group_id=${GROUP_ID}
consumer.max_attempts=${MAX_ATTEMPTS}
consumer.backoff_delay=${BACKOFF_DELAY}
consumer.concurrency=${CONCURRENT_LISTENER_INSTANCES}

logger.namespace=alphabetical-company-search-consumer

api.api-url=${API_URL:localhost}
api.api-key=${CHS_API_KEY:chsApiKey}
api.alphabetical-search-uri=${ALPHABETICAL_SEARCH_URI:/alphabetical-search/companies}

logging.level.org.apache.kafka.clients: ${KAFKA_LOGGING_LEVEL:INFO}
logging.level.org.apache.kafka: ${KAFKA_LOGGING_LEVEL:INFO}
logging.level.org.springframework.kafka: ${KAFKA_LOGGING_LEVEL:INFO}
logging.level.org.springframework.kafka.listener: ${KAFKA_LOGGING_LEVEL:INFO}
